services:
  michibiki:
    build: .
    container_name: michibiki
    restart: unless-stopped
    environment:
      - SUWAYOMI_URL=http://10.10.10.4:4567/api/graphql
      - ANILIST_TOKEN=${ANILIST_TOKEN}
      - POLL_INTERVAL_SECONDS=86400
      - DRY_RUN=${DRY_RUN:-true}
      - BACKUP_DIR=/app/backups
      - MODE=watch
      - POPULATE_SUWAYOMI=${POPULATE_SUWAYOMI:-true}
      - CLEAR_SUWAYOMI_FIRST=${CLEAR_SUWAYOMI_FIRST:-false}
    volumes:
      - michibiki_data:/app/data
      - /home/syncthing/data/mihon-backups:/app/backups

volumes:
  michibiki_data:
